spring:
  application:
    name: eurekaClient-01
  cloud:
    config:
      uri: http://localhost:8000
      profile: test
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url-path: /swagger-ui.html
    hostname: localhost