spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/lzp-aygx/SpringCloudConfig
          username:
          password:
          search-paths: /
server:
  port: 8000

