
package com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.concrete;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-14T15:57:32.732+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GenericFault", targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001")
public class GetInOutRecordsByCardIDFault extends Exception {
    
    private com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.GenericFault genericFault;

    public GetInOutRecordsByCardIDFault() {
        super();
    }
    
    public GetInOutRecordsByCardIDFault(String message) {
        super(message);
    }
    
    public GetInOutRecordsByCardIDFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetInOutRecordsByCardIDFault(String message, com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.GenericFault genericFault) {
        super(message);
        this.genericFault = genericFault;
    }

    public GetInOutRecordsByCardIDFault(String message, com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.GenericFault genericFault, Throwable cause) {
        super(message, cause);
        this.genericFault = genericFault;
    }

    public com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.GenericFault getFaultInfo() {
        return this.genericFault;
    }
}
