
package com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.concrete;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-14T15:57:32.775+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "PublishVehicleInOutRecordFault", targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001")
public class PublishVehicleInOutRecordFault extends Exception {
    
    private com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.PublishVehicleInOutRecordFault publishVehicleInOutRecordFault;

    public PublishVehicleInOutRecordFault() {
        super();
    }
    
    public PublishVehicleInOutRecordFault(String message) {
        super(message);
    }
    
    public PublishVehicleInOutRecordFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PublishVehicleInOutRecordFault(String message, com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.PublishVehicleInOutRecordFault publishVehicleInOutRecordFault) {
        super(message);
        this.publishVehicleInOutRecordFault = publishVehicleInOutRecordFault;
    }

    public PublishVehicleInOutRecordFault(String message, com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.PublishVehicleInOutRecordFault publishVehicleInOutRecordFault, Throwable cause) {
        super(message, cause);
        this.publishVehicleInOutRecordFault = publishVehicleInOutRecordFault;
    }

    public com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.PublishVehicleInOutRecordFault getFaultInfo() {
        return this.publishVehicleInOutRecordFault;
    }
}
