package com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.concrete;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-14T15:57:32.806+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001/concrete", name = "VehicleGateControl")
@XmlSeeAlso({com.leemanpaper.schema.technology.framework.common.v001.ObjectFactory.class, com.leemanpaper.schema.logistics.transport.vehiclegatecontrol.v001.ObjectFactory.class, com.leemanpaper.schema.common.leemancommon.v001.ObjectFactory.class, com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VehicleGateControl {

    @WebResult(name = "GetInOutRecordsByCardIDResponse", targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001", partName = "parameters")
    @WebMethod(operationName = "GetInOutRecordsByCardID", action = "/Logistics/Transport/VehicleGateControl/v001/GetInOutRecordsByCardID")
    public com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.GetInOutRecordsByCardIDResponse getInOutRecordsByCardID(
        @WebParam(partName = "parameters", name = "GetInOutRecordsByCardID", targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001")
        com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.GetInOutRecordsByCardID parameters,
        @WebParam(partName = "request_header", name = "RequestHeader", targetNamespace = "http://www.leemanpaper.com/schema/technology/framework/Common/v001", header = true)
        com.leemanpaper.schema.technology.framework.common.v001.RequestHeaderType requestHeader
    ) throws GetInOutRecordsByCardIDFault;

    @WebResult(name = "GetLatestInOutRecordByLicensePlateResponse", targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001", partName = "parameters")
    @WebMethod(operationName = "GetLatestInOutRecordByLicensePlate", action = "/Logistics/Transport/VehicleGateControl/v001/GetLatestInOutRecordByLicensePlate")
    public com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.GetLatestInOutRecordByLicensePlateResponse getLatestInOutRecordByLicensePlate(
        @WebParam(partName = "parameters", name = "GetLatestInOutRecordByLicensePlate", targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001")
        com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.GetLatestInOutRecordByLicensePlate parameters,
        @WebParam(partName = "request_header", name = "RequestHeader", targetNamespace = "http://www.leemanpaper.com/schema/technology/framework/Common/v001", header = true)
        com.leemanpaper.schema.technology.framework.common.v001.RequestHeaderType requestHeader
    ) throws GetLatestInOutRecordByLicensePlateFault;

    @WebResult(name = "PublishVehicleInOutRecordResponse", targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001", partName = "parameters")
    @WebMethod(operationName = "PublishVehicleInOutRecord", action = "/Logistics/Transport/VehicleGateControl/v001/PublishVehicleInOutRecord")
    public com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.PublishVehicleInOutRecordResponse publishVehicleInOutRecord(
        @WebParam(partName = "parameters", name = "PublishVehicleInOutRecord", targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001")
        com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.PublishVehicleInOutRecord parameters,
        @WebParam(partName = "request_header", name = "RequestHeader", targetNamespace = "http://www.leemanpaper.com/schema/technology/framework/Common/v001", header = true)
        com.leemanpaper.schema.technology.framework.common.v001.RequestHeaderType requestHeader
    ) throws PublishVehicleInOutRecordFault;

    @WebResult(name = "GetLatestInOutRecordByCardIDResponse", targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001", partName = "parameters")
    @WebMethod(operationName = "GetLatestInOutRecordByCardID", action = "/Logistics/Transport/VehicleGateControl/v001/GetLatestInOutRecordByCardID")
    public com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.GetLatestInOutRecordByCardIDResponse getLatestInOutRecordByCardID(
        @WebParam(partName = "parameters", name = "GetLatestInOutRecordByCardID", targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001")
        com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.GetLatestInOutRecordByCardID parameters,
        @WebParam(partName = "request_header", name = "RequestHeader", targetNamespace = "http://www.leemanpaper.com/schema/technology/framework/Common/v001", header = true)
        com.leemanpaper.schema.technology.framework.common.v001.RequestHeaderType requestHeader
    ) throws GetLatestInOutRecordByCardIDFault;

    @WebResult(name = "GetInOutRecordsByLicensePlateResponse", targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001", partName = "parameters")
    @WebMethod(operationName = "GetInOutRecordsByLicensePlate", action = "/Logistics/Transport/VehicleGateControl/v001/GetInOutRecordsByLicensePlate")
    public com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.GetInOutRecordsByLicensePlateResponse getInOutRecordsByLicensePlate(
        @WebParam(partName = "parameters", name = "GetInOutRecordsByLicensePlate", targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001")
        com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.GetInOutRecordsByLicensePlate parameters,
        @WebParam(partName = "request_header", name = "RequestHeader", targetNamespace = "http://www.leemanpaper.com/schema/technology/framework/Common/v001", header = true)
        com.leemanpaper.schema.technology.framework.common.v001.RequestHeaderType requestHeader
    ) throws GetInOutRecordsByLicensePlateFault;
}
