package com.leemanpaper.wsdl.logistics.transport.vehiclegatecontrol.v001.concrete;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-14T15:57:32.834+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "VehicleGateControl_v001", 
                  wsdlLocation = "http://172.23.1.82:9990/Logistics/Transport/VehicleGateControl/v001",
                  targetNamespace = "http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001/concrete") 
public class VehicleGateControlV001 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001/concrete", "VehicleGateControl_v001");
    public final static QName VehicleGateControlHTTPEndpoint = new QName("http://www.leemanpaper.com/wsdl/logistics/transport/VehicleGateControl/v001/concrete", "VehicleGateControlHTTPEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://172.23.1.82:9990/Logistics/Transport/VehicleGateControl/v001");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VehicleGateControlV001.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/IdeaWorkSpace/advancedLearningPath/basicLearningPath/web/wsdl/VehicleGateControl_v001.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VehicleGateControlV001(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VehicleGateControlV001(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VehicleGateControlV001() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public VehicleGateControlV001(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VehicleGateControlV001(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VehicleGateControlV001(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns VehicleGateControl
     */
    @WebEndpoint(name = "VehicleGateControlHTTPEndpoint")
    public VehicleGateControl getVehicleGateControlHTTPEndpoint() {
        return super.getPort(VehicleGateControlHTTPEndpoint, VehicleGateControl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VehicleGateControl
     */
    @WebEndpoint(name = "VehicleGateControlHTTPEndpoint")
    public VehicleGateControl getVehicleGateControlHTTPEndpoint(WebServiceFeature... features) {
        return super.getPort(VehicleGateControlHTTPEndpoint, VehicleGateControl.class, features);
    }

}
